name: doge-art
version: '3.7.3'
summary: doge is a simple motd script
description: doge is a simple motd script based on the slightly stupid but very funny doge meme.

grade: stable
confinement: strict

apps: 
  doge:  
    command: doge

parts:
  doge:
    plugin: python
    python-version: python2
